class Explorer:
    def profile(self, path: str) -> dict: ...
    def drift(self, path: str) -> list[dict]: ...
    def preview(self, path: str) -> dict: ...
    def sql(self, path: str, query: str) -> dict: ...
